import React from 'react';
import { Language } from './types';

export const translations = {
  [Language.EN]: {
    appName: 'सब्ज़ीMATE',
    loginTitle: 'Welcome to सब्ज़ीMATE',
    loginSubtitle: 'Your daily fresh vegetable partner',
    loginWithPhone: 'Login with Phone',
    loginWithGoogle: 'Login with Google',
    chooseLanguage: 'Choose your language',
    english: 'English',
    hindi: 'हिन्दी',
    continue: 'Continue',
    home: 'Home',
    urgentOrder: 'Urgent Order',
    bills: 'Orders',
    history: 'History',
    willYouTakeVeg: 'Will you take vegetables today?',
    yes: 'YES',
    no: 'NO',
    todaysVeggies: "Today's Fresh Vegetables",
    searchPlaceholder: 'Search for vegetables...',
    deliveryConfirmation: "Thanks! We will stop at your house today.",
    noDeliveryConfirmation: "Okay! We will not stop at your house today. See you tomorrow!",
    optionalSelection: 'Optional: Select items you might need to help us stock the truck.',
    confirmSelection: 'Confirm Selection',
    urgentOrderTitle: 'Place an Urgent Order',
    urgentOrderDesc: 'Order anytime. A ₹20 delivery charge will apply.',
    placeOrder: 'Place Order',
    locationTitle: 'Live Truck Location',
    locationDesc: 'Our truck is on its way! Track its live location during delivery hours.',
    billsTitle: 'Your Order History & Bills',
    monthlyTotal: 'Monthly Total',
    payNow: 'Pay Now',
    payWithCash: 'Pay with Cash',
    loading: 'Loading...',
    // Onboarding & Profile
    setupProfile: 'Setup Your Profile',
    fullName: 'Full Name',
    phoneNumber: 'Phone Number',
    address: 'Delivery Address',
    useMap: 'Use Map',
    saveAndContinue: 'Save & Continue',
    yourProfile: 'Your Profile',
    edit: 'Edit',
    save: 'Save',
    // Modal
    updateOrder: 'Update Order',
    close: 'Close',
    // History
    orderHistory: 'Order History',
    reorderItems: 'Re-order Items',
    // Settings
    settings: 'Settings',
    account: 'Account',
    editProfile: 'Edit Profile',
    paymentPreference: 'Payment Preference',
    preferences: 'Preferences',
    language: 'Language',
    notifications: 'Notifications',
    about: 'About',
    logout: 'Logout',
    appVersion: 'App Version',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    // New Translations
    getOTP: 'Get OTP',
    verifyAndContinue: 'Verify & Continue',
    enterVerificationCode: 'Enter Verification Code',
    loginOrSignup: 'Login or Signup',
    enterMobilePrompt: 'Enter your 10-digit mobile number to begin.',
    enterOTPPrompt: 'Enter the 6-digit code we sent to',
    didNotReceiveCode: "Didn't receive a code?",
    resendIn: 'Resend in',
    resendOTP: 'Resend OTP',
    state: 'State',
    city: 'City',
    detecting: 'Detecting...',
    useMyLocation: 'Use My Current Location',
    orDivider: 'OR',
    logoutAndStartOver: 'Logout & Start Over',
    myDailyEssentials: 'My Daily Essentials',
    helpSupport: 'Help & Support',
    helpCenter: 'Help Center',
    contactUs: 'Contact Us',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    todaysRecipe: "Today's Special Recipe",
    recipe: 'Recipe',
    discoverDish: 'Discover a new dish to cook!',
    listening: 'Listening...',
    processing: 'Processing...',
    speakHere: 'Speak here',
    noVeggiesFound: 'No vegetables found.',
    unsavedItemsPrompt: 'You have unsaved items in your list!',
    saveNow: 'Save Now',
    reorderError: 'Could not re-order items. Please try again.',
    reorderUnavailable: 'None of the items from this order are available today.',
    items: 'items',
    item: 'item',
    paymentSuccess: 'Payment Successful!',
    myList: 'My List',
    // Categories
    all: 'All',
    leafy: 'Leafy Greens',
    root: 'Root Veggies',
    fruit: 'Fruit Veggies',
    other: 'Other',
  },
  [Language.HI]: {
    appName: 'सब्ज़ीMATE',
    loginTitle: 'सब्ज़ीMATE में आपका स्वागत है',
    loginSubtitle: 'आपका दैनिक ताजा सब्जी का साथी',
    loginWithPhone: 'फोन से लॉगिन करें',
    loginWithGoogle: 'गूगल से लॉगिन करें',
    chooseLanguage: 'अपनी भाषा चुनें',
    english: 'English',
    hindi: 'हिन्दी',
    continue: 'जारी रखें',
    home: 'होम',
    urgentOrder: 'जरूरी ऑर्डर',
    bills: 'ऑर्डर',
    history: 'हिस्ट्री',
    willYouTakeVeg: 'क्या आप आज सब्जियां लेंगे?',
    yes: 'हाँ',
    no: 'नहीं',
    todaysVeggies: 'आज की ताज़ा सब्ज़ियाँ',
    searchPlaceholder: 'सब्जियां खोजें...',
    deliveryConfirmation: "धन्यवाद! हम आज आपके घर पर रुकेंगे।",
    noDeliveryConfirmation: "ठीक है! हम आज आपके घर पर नहीं रुकेंगे। कल मिलते हैं!",
    optionalSelection: 'वैकल्पिक: उन वस्तुओं का चयन करें जिनकी आपको आवश्यकता हो सकती है ताकि हमें ट्रक स्टॉक करने में मदद मिल सके।',
    confirmSelection: 'चयन की पुष्टि करें',
    urgentOrderTitle: 'एक तत्काल आदेश दें',
    urgentOrderDesc: 'किसी भी समय ऑर्डर करें। ₹20 डिलीवरी शुल्क लागू होगा।',
    placeOrder: 'ऑर्डर दें',
    locationTitle: 'लाइव ट्रक लोकेशन',
    locationDesc: 'हमारा ट्रक रास्ते में है! डिलीवरी के घंटों के दौरान इसका लाइव लोकेशन ट्रैक करें।',
    billsTitle: 'आपके ऑर्डर और बिल',
    monthlyTotal: 'मासिक कुल',
    payNow: 'अभी भुगतान करें',
    payWithCash: 'नकद में भुगतान करें',
    loading: 'लोड हो रहा है...',
    // Onboarding & Profile
    setupProfile: 'अपनी प्रोफ़ाइल सेटअप करें',
    fullName: 'पूरा नाम',
    phoneNumber: 'फ़ोन नंबर',
    address: 'डिलीवरी का पता',
    useMap: 'नक्शे का प्रयोग करें',
    saveAndContinue: 'सहेजें और जारी रखें',
    yourProfile: 'आपकी प्रोफ़ाइल',
    edit: 'संपादित करें',
    save: 'सहेजें',
    // Modal
    updateOrder: 'ऑर्डर अपडेट करें',
    close: 'बंद करें',
     // History
    orderHistory: 'ऑर्डर हिस्ट्री',
    reorderItems: 'आइटम फिर से ऑर्डर करें',
    // Settings
    settings: 'सेटिंग्स',
    account: 'अकाउंट',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    paymentPreference: 'भुगतान प्राथमिकता',
    preferences: 'वरीयताएँ',
    language: 'भाषा',
    notifications: 'सूचनाएं',
    about: 'ऐप के बारे में',
    logout: 'लॉग आउट',
    appVersion: 'ऐप संस्करण',
    daily: 'दैनिक',
    weekly: 'साप्ताहिक',
    monthly: 'मासिक',
    // New Translations
    getOTP: 'OTP प्राप्त करें',
    verifyAndContinue: 'सत्यापित करें और जारी रखें',
    enterVerificationCode: 'सत्यापन कोड दर्ज करें',
    loginOrSignup: 'लॉग इन या साइनअप करें',
    enterMobilePrompt: 'शुरू करने के लिए अपना 10 अंकों का मोबाइल नंबर दर्ज करें।',
    enterOTPPrompt: 'हमने आपके नंबर पर जो 6-अंकीय कोड भेजा है, उसे दर्ज करें',
    didNotReceiveCode: 'कोड नहीं मिला?',
    resendIn: 'पुनः भेजें', // The number and 's' will be in English
    resendOTP: 'OTP पुनः भेजें',
    state: 'राज्य',
    city: 'शहर',
    detecting: 'पता लग रहा है...',
    useMyLocation: 'मेरी वर्तमान लोकेशन का उपयोग करें',
    orDivider: 'या',
    logoutAndStartOver: 'लॉगआउट करें और फिर से शुरू करें',
    myDailyEssentials: 'मेरी दैनिक आवश्यकताएं',
    helpSupport: 'सहायता और समर्थन',
    helpCenter: 'सहायता केंद्र',
    contactUs: 'संपर्क करें',
    privacyPolicy: 'गोपनीयता नीति',
    termsOfService: 'सेवा की शर्तें',
    todaysRecipe: "आज की विशेष रेसिपी",
    recipe: 'रसोई',
    discoverDish: 'पकाने के लिए एक नई डिश खोजें!',
    listening: 'सुन रहा है...',
    processing: 'प्रोसेस हो रहा है...',
    speakHere: 'यहां बोलें',
    noVeggiesFound: 'कोई सब्जी नहीं मिली।',
    unsavedItemsPrompt: 'आपकी सूची में सहेजे नहीं गए आइटम हैं!',
    saveNow: 'अभी सहेजें',
    reorderError: 'आइटम फिर से ऑर्डर नहीं कर सका। कृपया पुन: प्रयास करें।',
    reorderUnavailable: 'इस ऑर्डर की कोई भी वस्तु आज उपलब्ध नहीं है।',
    items: 'आइटम',
    item: 'आइटम',
    paymentSuccess: 'भुगतान सफल!',
    myList: 'मेरी सूची',
    // Categories
    all: 'सब',
    leafy: 'पत्तेदार सब्ज़ियाँ',
    root: 'जड़ वाली सब्ज़ियाँ',
    fruit: 'फल सब्ज़ियाँ',
    other: 'अन्य',
  },
};