import React, { useState, useContext } from 'react';
import { AuthContext } from '@common/AuthContext';
import * as api from '@common/api';
import LoadingSpinner from '@common/components/LoadingSpinner';

const ManageSecurity: React.FC = () => {
    const auth = useContext(AuthContext);
    const [is2FAEnabled, setIs2FAEnabled] = useState(auth.user?.isTwoFactorEnabled || false);
    const [isLoading, setIsLoading] = useState(false);
    const [setupData, setSetupData] = useState<{ qrCodeUrl: string } | null>(null);
    const [verificationCode, setVerificationCode] = useState('');
    const [error, setError] = useState('');

    const startSetup = async () => {
        setIsLoading(true);
        setError('');
        try {
            const data = await api.generate2FASecret();
            setSetupData(data);
        } catch (err: any) {
            setError(err.message || 'Could not start 2FA setup.');
        } finally {
            setIsLoading(false);
        }
    };

    const confirmSetup = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!verificationCode) return;
        setIsLoading(true);
        setError('');
        try {
            await api.enable2FA(verificationCode);
            alert('2FA has been enabled successfully!');
            // Update local state and auth context
            setIs2FAEnabled(true);
            if (auth.user) {
                auth.updateUserSession({ ...auth.user, isTwoFactorEnabled: true });
            }
            setSetupData(null);
            setVerificationCode('');
        } catch (err: any) {
            setError(err.message || 'Verification failed. The code may be incorrect or expired.');
        } finally {
            setIsLoading(false);
        }
    };

    const disable2FA = async () => {
        if (!window.confirm('Are you sure you want to disable 2FA? This will reduce your account security.')) {
            return;
        }
        setIsLoading(true);
        setError('');
        try {
            await api.disable2FA();
            alert('2FA has been disabled.');
            setIs2FAEnabled(false);
            if (auth.user) {
                auth.updateUserSession({ ...auth.user, isTwoFactorEnabled: false });
            }
        } catch (err: any) {
            setError(err.message || 'Could not disable 2FA.');
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div className="max-w-2xl mx-auto bg-white p-8 rounded-lg shadow-md">
            <h2 className="text-2xl font-bold text-gray-800 mb-4">Account Security</h2>

            {is2FAEnabled ? (
                <div>
                    <p className="text-gray-600 mb-4">
                        Two-Factor Authentication is currently <span className="font-bold text-green-600">ENABLED</span> on your account,
                        providing an extra layer of security.
                    </p>
                    <button
                        onClick={disable2FA}
                        disabled={isLoading}
                        className="bg-red-600 text-white font-bold py-2 px-4 rounded-lg hover:bg-red-700 disabled:bg-gray-400"
                    >
                        {isLoading ? 'Disabling...' : 'Disable 2FA'}
                    </button>
                </div>
            ) : setupData ? (
                <div>
                    <h3 className="text-lg font-bold">Set up 2FA</h3>
                    <p className="text-gray-600 my-4">
                        1. Scan the QR code below with your authenticator app (e.g., Google Authenticator, Authy).
                    </p>
                    <div className="flex justify-center my-6">
                        <img src={setupData.qrCodeUrl} alt="2FA QR Code" className="border-4 border-gray-300 rounded-lg"/>
                    </div>
                    <p className="text-gray-600 my-4">
                        2. Enter the 6-digit code generated by your app to complete the setup.
                    </p>
                    <form onSubmit={confirmSetup} className="flex items-center space-x-3">
                        <input
                            type="text"
                            value={verificationCode}
                            onChange={(e) => setVerificationCode(e.target.value.replace(/\D/g, ''))}
                            maxLength={6}
                            placeholder="6-digit code"
                            className="flex-grow px-3 py-2 bg-white border border-gray-300 rounded-md shadow-sm"
                            required
                        />
                        <button type="submit" disabled={isLoading} className="bg-green-600 text-white font-bold py-2 px-4 rounded-lg hover:bg-green-700 disabled:bg-gray-400">
                            {isLoading ? 'Verifying...' : 'Enable'}
                        </button>
                    </form>
                </div>
            ) : (
                <div>
                    <p className="text-gray-600 mb-4">
                        Enhance your account's security by enabling Two-Factor Authentication (2FA). You will be required
                        to enter a code from your authenticator app each time you log in.
                    </p>
                    <button
                        onClick={startSetup}
                        disabled={isLoading}
                        className="bg-blue-600 text-white font-bold py-2 px-4 rounded-lg hover:bg-blue-700 disabled:bg-gray-400"
                    >
                        {isLoading ? 'Loading...' : 'Enable 2FA'}
                    </button>
                </div>
            )}
            {error && <p className="text-red-500 text-sm mt-4">{error}</p>}
        </div>
    );
};

export default ManageSecurity;